sudo: required
language: java
dist: trusty
jdk: oraclejdk8
addons:
  ssh_known_hosts:
    - 39.105.147.203:22008
    - 39.105.147.203:22008
    - 39.105.147.203:22008
  sonarcloud:
    organization: tron-zhaohong
    token:
      secure: "KXWEeQ1elAoQ0XfR54TQWfhrIdDP0+2CYPv2X9aWpU/YDl7hqZBAjcCOAUGvlbyM54jtG6YMaWwG48jlrOwwl5l/VjWSnUXF+7ixQy5ki0Ci9s7Y1pTQwV9SpL8TLIK2TYqabN8Mw+FJULASXLjYr9GerbbcUbCPTmcL6mQKw6ivxxpNPmz4eNoKAEuOzruO9fTXGAV3yr8Nn85c+mVxV8EUhkR17zpE9O8fvzOtSnYArWNOSCgDBn0EG45UNNPF2vn44s1c3h3gX1m3WK6PeCXPgy3hPqRn3wTG+xglnbqthGpo2wt1rJ83af+BwdYwvPEcUq84yLgXcE/aMkTKcVAfPWBP/6vblaoI90jxCeFji+MdMimKZAqIXt7oLqDZVmIq65de5YC5s7QTSbzJNY/tsAu3dqzSfbUJY6CRNFDcoenVpvgQkqb37TkDah4mJM8EUjbu2A9Q2HSFbyCVsQJtdasuu9cBOf6azK3U0XgFNBc0y2aziZrTnX30q7bi+5L/mbTnRdXrDqBOqyPeGtT77UZfcajHHmEWU/e6gYWiA/c+K25n13DD53Au6gpnnQ6ALeUl/1gDwz3fPBebJ5bVWrkIcLj7bbysjzfOvQmDS6G13RNz58Hm0/B7bVtZTr1E1q6Z1zEJwbuJYEJASNcezAfK5x/hIfZTGNqT3M8="
cache:
  directories:
    - '$HOME/.sonar/cache'
matrix:
  include:
  - name: build
    script:
    - cd dapp-chain/side-chain
    - sh tron.sh
    - "./gradlew build"
    - "./gradlew jacocoTestReport"


  - name: stest
    script:
    - cd dapp-chain/side-chain
    - sh tron.sh
    - bash deploy.sh



after_success:
- cd dapp-chain/side-chain
- "bash <(curl -s https://codecov.io/bash) -t 060bb400-c6fe-4d5f-a6c8-427105c746ac -s /build/reports/jacoco/"

skip_build:
- README.md：
- LICENSE




